# Generated by Django 5.2.13 on 2026-05-05 10:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('organisme', models.CharField(max_length=200, verbose_name='Institution émettrice')),
                ('description', models.TextField(verbose_name="Résumé de l'offre")),
                ('pays', django_countries.fields.CountryField(default='BF', max_length=2)),
                ('date_publication', models.DateField()),
                ('date_cloture', models.DateField()),
                ('url_tdr', models.URLField(blank=True, null=True, unique=True, verbose_name='Lien source officiel (si existe)')),
                ('mode_acquisition', models.CharField(choices=[('AUTO', 'Collecte Automatique (Scraping)'), ('MANUEL', 'Saisie Manuelle (Administrateur)')], default='AUTO', max_length=10)),
                ('statut', models.CharField(default='Ouvert', max_length=50)),
            ],
            options={
                'verbose_name': "Appel d'Offre",
                'verbose_name_plural': "Appels d'Offres",
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du site source')),
                ('url_racine', models.URLField(verbose_name="Lien de la page d'accueil")),
                ('frequence_maj', models.CharField(help_text='Ex: Toutes les 12 heures', max_length=50)),
                ('est_actif', models.BooleanField(default=True, help_text='Désactiver si le site change de structure')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('EXPERT', 'Expert'), ('VISITEUR', 'Visiteur'), ('BUREAU', "Bureau d'étude / Entreprise")], default='VISITEUR', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BureauEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(max_length=200)),
                ('domaine_activite', models.CharField(max_length=200)),
                ('email_contact', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=20)),
                ('gestionnaire', models.OneToOneField(limit_choices_to={'role': 'BUREAU'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CritereRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots_cles', models.CharField(help_text="Ex: 'Forage', 'Audit informatique'", max_length=255)),
                ('description_recherchee', models.TextField(blank=True, verbose_name='Description détaillée du besoin')),
                ('alerte_active', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offre_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offres.appeloffre')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ProfilExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_competence', models.CharField(help_text='Ex: Infrastructures, IT, Finance', max_length=255)),
                ('cv_fichier', models.FileField(upload_to='cv_experts/', verbose_name='CV (PDF)')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'EXPERT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='source_origine',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si c'est une publication manuelle", null=True, on_delete=django.db.models.deletion.SET_NULL, to='offres.sourcescraping'),
        ),
    ]
