# Generated by Django 5.2.14 on 2026-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcescraping',
            options={'verbose_name': 'Sources de scraping'},
        ),
        migrations.AddField(
            model_name='sourcescraping',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier scraping'),
        ),
    ]
