# Generated by Django 5.2.13 on 2026-05-05 11:51

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, default='BF', max_length=2, verbose_name='Pays de résidence'),
        ),
    ]
