# Generated by Django 5.2.13 on 2026-05-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_utilisateur_adresse_utilisateur_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suggestion', models.DateTimeField(auto_now_add=True)),
                ('commentaire_admin', models.TextField(blank=True, help_text='Pourquoi suggérer cet expert ?')),
                ('est_consulte_par_expert', models.BooleanField(default=False)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.profilexpert', verbose_name='Expert sélectionné')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.appeloffre', verbose_name='Offre concernée')),
            ],
            options={
                'verbose_name': "Suggestion d'expert",
                'unique_together': {('expert', 'offre')},
            },
        ),
    ]
