# Generated by Django 5.2.14 on 2026-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_alter_sourcescraping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcescraping',
            options={'verbose_name': 'Source de scraping', 'verbose_name_plural': 'Sources de scraping'},
        ),
        migrations.AddField(
            model_name='sourcescraping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcescraping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='sourcescraping',
            table=None,
        ),
    ]
