# Generated by Django 5.2.14 on 2026-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0003_alter_sourcescraping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('EXPERT', 'Expert'), ('BUREAU', "Bureau d'étude / Entreprise")], default='Utilisateur', max_length=20),
        ),
    ]
