# Generated by Django 5.2.14 on 2026-05-14 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='url_source',
            field=models.URLField(blank=True, help_text="Page web où l'offre est listée", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bureauetude',
            name='cv_fichier',
            field=models.FileField(blank=True, null=True, upload_to='cv_bureaux/', verbose_name='Documents structure'),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='source_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offres.sourcescraping'),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='statut',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('Clôturé', 'Clôturé'), ('Annulé', 'Annulé'), ('En cours', 'En cours')], default='Ouvert', max_length=20),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='url_tdr',
            field=models.URLField(blank=True, help_text='Lien direct vers le document officiel (PDF/DOC)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='critererecherche',
            name='utilisateur',
            field=models.ForeignKey(limit_choices_to={'role': 'EXPERT'}, on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('EXPERT', 'Expert'), ('BUREAU', "Bureau d'étude / Entreprise")], default='EXPERT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='suggestionoffre',
            unique_together={('expert', 'offre')},
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['statut', 'date_cloture'], name='Appel_Offre_statut_f0660f_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['pays', 'statut'], name='Appel_Offre_pays_d905a8_idx'),
        ),
    ]
