# Generated by Django 5.2.14 on 2026-05-18 10:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0005_appeloffre_url_source_bureauetude_cv_fichier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-date_publication'], 'verbose_name': "Appels d'Offres"},
        ),
        migrations.RemoveField(
            model_name='bureauetude',
            name='cv_fichier',
        ),
        migrations.RemoveField(
            model_name='critererecherche',
            name='description_recherchee',
        ),
        migrations.RemoveField(
            model_name='profilexpert',
            name='domaine_competence',
        ),
        migrations.AddField(
            model_name='bureauetude',
            name='adresse',
            field=models.TextField(default='', verbose_name='Adresse complète'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bureauetude',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bureauetude',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bureauetude',
            name='pays',
            field=django_countries.fields.CountryField(default='BF', max_length=2, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='bureauetude',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='critererecherche',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critererecherche',
            name='domaines',
            field=models.CharField(blank=True, help_text='Domaines recherchés', max_length=500),
        ),
        migrations.AddField(
            model_name='critererecherche',
            name='frequence',
            field=models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='critererecherche',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='critererecherche',
            name='nom_critere',
            field=models.CharField(blank=True, help_text='Nom du critère (ex: Offres IT)', max_length=100),
        ),
        migrations.AddField(
            model_name='critererecherche',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, default='BF', max_length=2, verbose_name='Filtrer par pays'),
        ),
        migrations.AddField(
            model_name='profilexpert',
            name='autres_competences',
            field=models.TextField(blank=True, help_text='Autres compétences'),
        ),
        migrations.AddField(
            model_name='profilexpert',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilexpert',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible pour mission'),
        ),
        migrations.AddField(
            model_name='profilexpert',
            name='domaines_competence',
            field=models.CharField(blank=True, help_text='Sélectionnez vos domaines de compétence', max_length=500),
        ),
        migrations.AlterField(
            model_name='bureauetude',
            name='domaine_activite',
            field=models.CharField(max_length=200, verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='bureauetude',
            name='email_contact',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='bureauetude',
            name='gestionnaire',
            field=models.OneToOneField(limit_choices_to={'role': 'BUREAU'}, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_etude', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bureauetude',
            name='nom_structure',
            field=models.CharField(max_length=200, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='bureauetude',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='critererecherche',
            name='alerte_active',
            field=models.BooleanField(default=True, help_text='Recevoir des alertes email'),
        ),
        migrations.AlterField(
            model_name='critererecherche',
            name='mots_cles',
            field=models.CharField(help_text='Mots-clés recherchés (séparés par des virgules)', max_length=500),
        ),
        migrations.AlterField(
            model_name='critererecherche',
            name='utilisateur',
            field=models.ForeignKey(limit_choices_to={'role': 'EXPERT'}, on_delete=django.db.models.deletion.CASCADE, related_name='criteres_recherche', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilexpert',
            name='cv_fichier',
            field=models.FileField(blank=True, null=True, upload_to='cv_experts/%Y/%m/%d/', verbose_name='CV (PDF)'),
        ),
        migrations.AlterField(
            model_name='profilexpert',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'EXPERT'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
