# Generated by Django 5.2.14 on 2026-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0008_historiqueconnexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='mode_acquisition',
            field=models.CharField(choices=[('AUTO', 'Collecte Automatique (Scraping)'), ('MANUEL', 'Saisie Manuelle (Administrateur)'), ('API', 'Import via API externe'), ('IMPORT', 'Import fichier (CSV/Excel)')], default='AUTO', help_text="Mode d'acquisition de l'offre", max_length=50),
        ),
    ]
