# Generated by Django 5.2.14 on 2026-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0009_alter_appeloffre_mode_acquisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='pays',
            field=models.CharField(default='BF', help_text='Code pays ou region (BF, SN, MULTI, REGIONAL, et.)', max_length=10),
        ),
    ]
