# Generated by Django 5.2.14 on 2026-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0010_alter_appeloffre_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tdr/%y/%m/%d/', verbose_name='Fichier PDF (TDR)'),
        ),
    ]
