# Generated by Django 5.2.14 on 2026-06-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0011_appeloffre_fichier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='est_reponse',
            field=models.BooleanField(default=False, help_text='True si ce message est une réponse'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_original',
            field=models.ForeignKey(blank=True, help_text='Message original auquel cette réponse est liée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='offres.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='reponse_contenu',
            field=models.TextField(blank=True, help_text='Contenu de la réponse envoyée', null=True),
        ),
    ]
