# Generated by Django 5.2.14 on 2026-06-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0012_message_est_reponse_message_message_original_and_more'),
    ]

    operations = [
    ]
