# Generated by Django 5.2.14 on 2026-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0013_add_pays_field_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescraping',
            name='pays',
            field=models.CharField(blank=True, default='BF', max_length=10),
        ),
    ]
