# Generated by Django 5.2.14 on 2026-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0014_sourcescraping_pays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-date_publication', '-last_scraped_at']},
        ),
        migrations.RemoveIndex(
            model_name='appeloffre',
            name='Appel_Offre_statut_f0660f_idx',
        ),
        migrations.RemoveIndex(
            model_name='appeloffre',
            name='Appel_Offre_pays_d905a8_idx',
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='est_expire',
            field=models.BooleanField(default=False, editable=False, verbose_name='Offre expirée'),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la dernière récupération de cette offre', null=True, verbose_name='Dernier scraping'),
        ),
        migrations.AlterModelTable(
            name='appeloffre',
            table=None,
        ),
    ]
