# Generated by Django 5.2.14 on 2026-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0015_alter_appeloffre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-date_publication'], 'verbose_name': "Appels d'Offres"},
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='est_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['statut', 'date_cloture'], name='Appel_Offre_statut_f0660f_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['pays', 'statut'], name='Appel_Offre_pays_d905a8_idx'),
        ),
        migrations.AlterModelTable(
            name='appeloffre',
            table='Appel_Offre',
        ),
    ]
