# Generated by Django 5.2.14 on 2026-06-16 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0016_alter_appeloffre_options_alter_appeloffre_est_expire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-date_publication'], 'verbose_name': "Appels d'Offres", 'verbose_name_plural': "Appels d'Offres"},
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='last_scraped_at',
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_scraping',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date et heure exactes de la collecte automatique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='est_expire',
            field=models.BooleanField(default=False, help_text="Indique si l'offre est marquée comme expirée"),
        ),
    ]
