# Generated by Django 5.2.14 on 2026-06-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0017_alter_appeloffre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcescraping',
            options={'ordering': ['id'], 'verbose_name': 'Source de scraping', 'verbose_name_plural': 'Sources de scraping'},
        ),
        migrations.AlterModelOptions(
            name='suggestionoffre',
            options={'ordering': ['-id'], 'verbose_name': "Suggestion d'Expert pour une Offre"},
        ),
    ]
