# Generated by Django 5.2.14 on 2026-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0018_alter_sourcescraping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='date_scraping',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de collecte'),
        ),
    ]
