# Generated by Django 5.2.14 on 2026-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='description',
            field=models.TextField(blank=True, help_text="Description optionnelle de l'offre", null=True, verbose_name="Résumé de l'offre"),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Téléchargez le PDF depuis votre PC ou téléphone', null=True, upload_to='tdr/%Y/%m/%d/', verbose_name='Fichier PDF (TDR)'),
        ),
    ]
