# Generated by Django 5.2.14 on 2026-06-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0021_alter_appeloffre_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionoffre',
            options={'ordering': ['-date_suggestion'], 'verbose_name': "Suggestion d'Expert pour une Offre"},
        ),
        migrations.AddField(
            model_name='suggestionoffre',
            name='commentaire_expert',
            field=models.TextField(blank=True, help_text="Réponse de l'expert à la suggestion", verbose_name="Commentaire de l'expert"),
        ),
        migrations.AddField(
            model_name='suggestionoffre',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AddField(
            model_name='suggestionoffre',
            name='statut_reponse',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONSULTEE', 'Consultée'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de la réponse'),
        ),
        migrations.AlterField(
            model_name='suggestionoffre',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_recues', to='offres.profilexpert', verbose_name='Expert sélectionned'),
        ),
        migrations.AlterField(
            model_name='suggestionoffre',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='offres.appeloffre', verbose_name='Offre concernée'),
        ),
    ]
