# Generated by Django 5.2.14 on 2026-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0022_alter_suggestionoffre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='domaine',
            field=models.CharField(blank=True, db_index=True, help_text="Domaine de l'offre (IT & Digital, Santé & Médical, Ingénierie & Construction, etc.)", max_length=100, null=True, verbose_name="Domaine d'activité"),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['domaine'], name='Appel_Offre_domaine_f9c24b_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['pays', 'domaine'], name='Appel_Offre_pays_e28628_idx'),
        ),
    ]
