# Generated by Django 5.2.14 on 2026-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0023_appeloffre_domaine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescraping',
            name='delay',
            field=models.IntegerField(default=2, help_text="Temps d'attente entre chaque page pour éviter le blocage", verbose_name='Délai entre requêtes (secondes)'),
        ),
        migrations.AddField(
            model_name='sourcescraping',
            name='parser',
            field=models.CharField(blank=True, help_text='Laisser vide pour détection automatique. Options: undp, unfpa, agetib, sonabel, uemoa, joffres, smart', max_length=50, null=True, verbose_name='Type de parser'),
        ),
        migrations.AddField(
            model_name='sourcescraping',
            name='use_js',
            field=models.BooleanField(default=False, help_text='Activer si le site nécessite JavaScript pour afficher les offres', verbose_name='Utiliser Selenium (JavaScript)'),
        ),
    ]
