# Generated by Django 5.2.14 on 2026-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0024_sourcescraping_delay_sourcescraping_parser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='type_offre',
            field=models.CharField(choices=[('APPEL_D_OFFRES', "Appel d'offres (RFQ/RFP)"), ('APPEL_A_PROJETS', 'Appel à projets'), ('MANIFESTATION_INTERET', "Manifestation d'intérêt (EOI)"), ('RECRUTEMENT', 'Recrutement / Consultant'), ('VENTE_AUX_ENCHERES', 'Vente aux enchères'), ('AUTRE', 'Autre')], db_index=True, default='APPEL_D_OFFRES', help_text="Type d'offre (Appel d'offres, Appel à projets, etc.)", max_length=50, verbose_name="Type d'offre"),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['type_offre'], name='Appel_Offre_type_of_2103ab_idx'),
        ),
    ]
