# Generated by Django 4.2.16 on 2026-07-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0025_appeloffre_type_offre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Nom d'utilisateur ou email", max_length=200)),
                ('encrypted_password', models.TextField(help_text='Mot de passe chiffré')),
                ('login_url', models.URLField(blank=True, help_text='URL de la page de connexion (ex: https://example.com/login)')),
                ('auth_type', models.CharField(choices=[('FORM', 'Formulaire HTML'), ('BASIC', 'Basic Auth'), ('TOKEN', 'Token API'), ('SELENIUM', 'Selenium (JavaScript)')], default='FORM', help_text="Type d'authentification utilisé par le site", max_length=20)),
                ('username_field', models.CharField(default='username', help_text="Nom du champ HTML pour le username (ex: 'email', 'username', 'login')", max_length=100)),
                ('password_field', models.CharField(default='password', help_text='Nom du champ HTML pour le password', max_length=100)),
                ('username_selector', models.CharField(blank=True, help_text="Sélecteur CSS pour le champ username (ex: '#email', 'input[name=email]')", max_length=200)),
                ('password_selector', models.CharField(blank=True, help_text='Sélecteur CSS pour le champ password', max_length=200)),
                ('submit_selector', models.CharField(blank=True, help_text="Sélecteur CSS pour le bouton submit (ex: 'button[type=submit]')", max_length=200)),
                ('success_indicator', models.CharField(blank=True, help_text="Texte ou sélecteur qui confirme la connexion réussie (ex: 'logout', '.user-menu')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='offres.sourcescraping')),
            ],
            options={
                'verbose_name': 'Identifiants source',
                'verbose_name_plural': 'Identifiants sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
